### ISSUE TITLE
bin/poker_server non-functional

### ISSUE THREAD

**Issue by joshuaknox** [cortesoft/PokerMatic#1]
mk-II:PokerMatic (master) $ bin/poker_server 
Starting up server
NoMethodError: undefined method `find_or_create_application' for #Spire::API::Session:0x2073b879

**Comment by joshuaknox** [comment]
Apparently, the result of the --pre flag having been processed incorrectly, or general PEBKAC. 

Notably, the command doesn't c&p correctly due to parsing -- as a single character double-dash.

**Comment by cortesoft** [comment]
Sorry for taking so long to get back.  The --pre is actually not needed anymore, and I forgot to remove the line from the README.  You can just do 'jgem install spire_io' and you should get the right version.  The version that I am working off of is 1.2.4.
